server {
    listen 8080;
    root /usr/share/nginx/html;
    autoindex on;                        # listado sencillo
    types {
      text/plain txt;
      application/vnd.oasis.opendocument.spreadsheet ods;
      application/vnd.openxmlformats-officedocument.spreadsheetml.sheet xlsx;
    }
}
